/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 laysModel.glb
Author: NKaap (https://sketchfab.com/nkaap)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lays-classic-hd-textures-free-download-d6cbb11c15ab4db4a100a4e694798279
Title: Lays Classic || HD Textures || FREE Download!
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Model({ props, currentState, setCurrentState, setHover }) {
  const { nodes, materials } = useGLTF('/laysModel.glb')
  const group = useRef()

  return (
    <group
    ref={group} {...props}
    dispose={null}
    onPointerOver={(e) => {
      e.stopPropagation();
      setHover(e.object.material.name);
    }}
    onPointerOut={(e) => {
      e.intersections.length === 0 && setHover(null);
    }}
    onPointerMissed={() => {
      setCurrentState(null);
    }}
    onClick={(e) => {
      e.stopPropagation();
      setCurrentState(e.object.material.name);
    }}>

      <mesh geometry={nodes.Dorrito001_Lays_0.geometry} material={materials.Lays} scale={.04} material-color={currentState.items.Lays} />
    </group>
  )
}

useGLTF.preload('/laysModel.glb')
